### ISSUE TITLE
Visually Its working but functional Not 

### ISSUE THREAD

**Issue by kirangsa** [IonDen/ion.checkRadio#14]
Hi There,

I have tried to put check box 
```
<ul>
 <li>
 <label><input type="checkbox" name="Overall" value="0" id="kiran" />Overall</label>
 </li>

 <li>
 <label><input type="checkbox" name="bussiness" value="1" id="arun" />Overall</label>
 </li>
<.ul>
</code>
```
and Visually  the selection is working but i checkd e the input box is 
$('#kiran').is(":checked") its giving false on both condition.

**Comment by Odyldzhon** [comment]
I don't know where it's message should be, but I faced with same problem. I changed part of "checkOn", "checkOff" functions:
$input.prop("checked", "checked"); --> $input.prop("checked", true); 
$input.removeProp("checked"); --> $input.prop("checked", false);
and all works fine. IonDen thanks for this beautiful plugin, check maybe it's bug.

**Comment by IonDen** [comment]
Should be ok in 2.0.0
