### ISSUE TITLE
When using name as an array

### ISSUE THREAD

**Issue by laviku** [IonDen/ion.checkRadio#16]
The style of the element is not working when using the name as an array

 `<input name="field[]" id="checkboxes-0" value="1" type="checkbox">`

![screenshot_1](https://cloud.githubusercontent.com/assets/5578754/6694051/fca638e8-cc9c-11e4-8ac4-bfa0f8e0d6e9.png)

**Comment by IonDen** [comment]
Should be ok in 2.0.0
