### ISSUE TITLE
losing triggers on original input fields

### ISSUE THREAD

**Issue by joelharkes** [IonDen/ion.checkRadio#19]
I used your plugin to prettify my radio buttons, only i found one penalty. 
I lost my original working of code. 
I Expect the code to fire on change event when i click on the radio button, but this no longer is true. instead in listens to the onchange event of the hidden radio button and acts accordingly, but not backwards. can you please fix this?

**Comment by IonDen** [comment]
Hi, now you should use predefined code style, it will not repace original inputs with new ones, and also you will not loose original listeners.

**Comment by IonDen** [comment]
http://ionden.com/a/plugins/ion.checkRadio/demo.html
Check section "Recommended predefined layout. For advanced developers"
