### ISSUE TITLE
Лишние события

### ISSUE THREAD

**Issue by eugene-lazarev** [IonDen/ion.checkRadio#8]
Не вижу необходимости триггерить событие «stateChanged» у всех радиобаттонов группы — в частности у тех, у которых состояние не меняется.

Пример.
Три радиобаттона. Ни один не выбран.
Я выбираю второй.
В итоге событие «stateChanged» срабатывает у каждого из трёх радиобаттонов, хотя у №1 и №3 state совсем даже не changed.

**Comment by IonDen** [comment]
Should be ok in 2.0.0
